name: air_boltic_dbt
version: 1.0.0
config-version: 2

profile: air_boltic_dbt

quoting:
  database: false
  schema: true         # ✅ This tells dbt to quote boltic-data-raw
  identifier: false

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  air_boltic_dbt:       # ✅ Must match `name:` above
    staging:
      +materialized: table
    marts:
      +materialized: table