name: air_boltic_dbt
version: 1.0.0
config-version: 2

profile: air_boltic_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]

quoting:
  database: false
  schema: true          # ✅ dbt will add backticks for the schema
  identifier: false

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  air_boltic_dbt:       # ✅ Must match `name:` above
    staging:
      +materialized: table
    marts:
      +materialized: table