name: air_boltic_dbt
version: 1.0.0
config-version: 2

profile: air_boltic_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]

quoting:
  database: false
  schema: true
  identifier: false

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  air_boltic_dbt:
    01_staging:
      +materialized: table
    02_intermediate:
      +materialized: table
    03_marts:
      +materialized: table